name: Release Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-service:
    name: Release Docker image
    runs-on: ubuntu-latest
    # if: contains(github.event.commits.message, 'Version Packages')
    strategy:
      matrix:
        include:
          - image: ghcr.io/${{github.repository_owner}}/cerberus
            dockerfile: ./Dockerfile
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: replace token
        run: |
          echo -e "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > "./.npmrc"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ secrets.NPM_TOKEN }}
        # env:
        #   NPM_TOKEN: ${{secrets.NPM_TOKEN}}
